Calcula la matriu resultant y diagonalitza-la:


In [1]:
import numpy as np

Definim les matrius

In [10]:
matriu_a=np.array([[4,1,2],[1,3,1],[2,1,4]])
matriu_b=np.array([[2,0,1],[0,3,0],[1,0,2]])

Multipliquem les matrius

In [11]:
resultat=np.dot(matriu_a,matriu_b)

In [12]:
print("Matriu resultant de la multiplicació")
print(resultat)

Matriu resultant de la multiplicació
[[10  3  8]
 [ 3  9  3]
 [ 8  3 10]]


Calculem els valors i vectors pròpis

In [13]:
eigenvalues, eigenvectors=np.linalg.eig(resultat)

Formem la matriu diagonal amb els valors propis

In [14]:
matriu_diagonal=np.diag(eigenvalues)

In [15]:
print("Matriu diagonalitzada")
print(matriu_diagonal)

Matriu diagonalitzada
[[19.68465844  0.          0.        ]
 [ 0.          2.          0.        ]
 [ 0.          0.          7.31534156]]
